### ISSUE TITLE
BrowserModule has already been loaded

### ISSUE THREAD

**Issue by bolota** [vitalii-andriiovskyi/ngx-owl-carousel-o#1]
Hi,

Thank you for this carousel.

I have a problem with your module, after I imported it, I’m getting: 

BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

I think is because of: BrowserAnimationsModule

Thank you

**Comment by sandiphob** [comment]
I concur, this great work!! Most likely BrowserAnimationsModule is being imported twice. I was reading on https://github.com/angular/angular/issues/15579#issuecomment-291218157 that BrowserAnimation should be import on root module. So I removed the import in the owl carasoul and it worked for me (folder fesm5).

**Comment by vitalii-andriiovskyi** [comment]
@bolota Thanks for reporting the issue. 
`BrowserAnimationsModule` exports `BrowserModule` and this causes the problem. However, it appears in the case of lazy loading modules which consume `ngx-owl-carousel-o`. In other cases, everything is fine. 

I removed import of `BrowserAnimationsModule` into the `CarouselModule` and published the new version of the library (v0.0.5). But now it's required to import `BrowserAnimationsModule` into root module which is `AppModule` in most cases.
