### ISSUE TITLE
Updating to Angular version 10

### ISSUE THREAD

**Issue by Olexandr-L** [vitalii-andriiovskyi/ngx-owl-carousel-o#100]
`Package "ngx-owl-carousel-o" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0-rc.0 || ^8.0.0" (extended), would install "10.0.2").`

**Comment by vitalii-andriiovskyi** [comment]
@Olexandr-L 

Updated. The latest version is `v4.0.0`
