### ISSUE TITLE
owl-items disappear [ removed from dom ] on window size change 

### ISSUE THREAD

**Issue by Luarb** [vitalii-andriiovskyi/ngx-owl-carousel-o#12]
I was facing this issue only in one of my owl carousels,
every time I changed the window size the owl-items get removed.

`<ng-template carouselSlide [id]="index"> `

when I removed the [id] they stooped disappearing,
also when I removed responsive option the bug didn't happen again.   

Although there were no errors on my console.

**Comment by vitalii-andriiovskyi** [comment]
The option `responsive` is intended to set the number of visible (active) slides according to the width of element  containing the carousel (`<div>`, for example).
``` typescript
  responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      740: {
        items: 3
      },
      940: {
        items: 4
      }
    },
```

If the width of element containing the carousel gets changed and its new value belongs to the different range, the carousel will set that number of visible (active) slides which is defined for that range. E.g., the current width of `<div class="carousel-wrapper">` is 950 px, the number of visible slides is 4. But when `window size change` fires and the new width of `<div class="carousel-wrapper">` becames `900px`, one active slide (active owl item) will disapper. The browser shows 3 slides. Before 4 `.owl-item`'s had css-class `.active`. Now just 3 `.owl-item`'s have this css-class.

If you want to have unchangeable number of active slides at any width of  `<div class="carousel-wrapper">`, remove the option `responsive` as you did.

**Comment by Luarb** [comment]
Thank you for your reply, I understand. 
Meanwhile I faced another issue. The owl items and the stage freezes to 0 if the carousel is called inside a display:none div and than when it goes display:block nothing changes until the window resize event.

**Comment by vitalii-andriiovskyi** [comment]
You can solve by this way:
```html
<div class="your-div">
 <ng-container *ngIf="display =='none' ? false : true">
   <owl-carousel-o [options]="customOptions">
     ...
   </owl-carousel-o>
 </ng-container>
</div>
```

`display` must be the prop of .ts file. 

However, this solution will rerender carousel any time after css-prop `display` of `<div>` will change from `none` to `block`.

Also carousel can be rerendered after change of length of the array containing data for slides. At the begining you can define this array as empty array and when `display` from `none` becomes `block` for the first time, you populate the array with data and carousel gets rendered correctly.

**Comment by Luarb** [comment]
Thank you again ! I don't know if should open an  new issue for this but there is also an error on universal server side rendering , it give me this error : this.winRef.timeOut is not a function. I change this.winRef with window, it solved the problem but still this is not the correct way I bet.

**Comment by akshata456** [comment]
> Thanks for reporting the issue with SSR. The problem is solved in new version `v1.0.5`. Install it and SSR should work correctly.

@vitalii-andriiovskyi i still face this issue in v1.2.0 .Please look into this.we used here SSR.

**Comment by vitalii-andriiovskyi** [comment]
@akshata456 

The newest version for A7 is `v1.2.1` and it has workaround for `this.winRef.setTimeout` for SSR. It shouldn't give you an error.

**Comment by akshata456** [comment]
@vitalii-andriiovskyi  I update this version but still carousel stage take 0 width and after resizing window it looks proper.

**Comment by vitalii-andriiovskyi** [comment]
It seems the DOM-element containing `owl-carousel-o` has the width of 0 at the moment the carousel starts rendering.

To understand this: carousel reads the width of its parent DOM-element and use it for futher calculations. After that it defines the width of stage and slides. And if the width of parent DOM-element changes after carousel started rendering, carousel doesn't notice that. So rendering the carousel should start after the width of parent DOM-element is stable (*ngIf could help in this case).

**Comment by farshad662** [comment]
I hade this issue and and fixed it by add an unique string ID to each ng-template inside carousel
dont forget ID should be string and unique
