### ISSUE TITLE
Sorting does not work.

### ISSUE THREAD

**Issue by YurchenkoAndrew** [vitalii-andriiovskyi/ngx-owl-carousel-o#128]
I have an array of slides data. By default, sorting is performed by id field. But I also have a sort field which I set as a sort field - which makes sense. When trying to send data sorted by the sort field from the backend, there is no display. Also, the [id] parameter swears at me constantly. Although I give him data in the required format = string.   [id]="slide.sort"

```
<div>Some tags before</div>
    <owl-carousel-o [options]="customOptions">

    <ng-container *ngFor="let slide of slidesStore">
      <ng-template carouselSlide [id]="slide.sort">
        <img [src]="slide.src" [alt]="slide.alt" [title]="slide.title">
      </ng-template>
    </ng-container>

  </owl-carousel-o>
  <div>Some tags after</div>
```

And also my PhpShtorm does not see the [id] parameter.
Question: Is it possible for the required tasks? Sort array elements of slides by custom field?
Angular 11

There is also one more question: Why is the "**string**" type selected for sorting? Although it is logical to use the type **number** !!!

**Comment by vitalii-andriiovskyi** [comment]
Hi @YurchenkoAndrew.
Sorry for late answear. 

> Why is the "string" type selected for sorting? Although it is logical to use the type number !!!

`ngx-owl-carousel-o` shows data (slides) in the order an array with data has. The lib has nothing in common with sorting. It just represents data provided by user. You change the data in array or better supply another array, and the lib will show slides with new data. 

Carousel uses self-generated or provided by user `id`s for own purposes. If user provides `id`s of slides, he can use it for further calculation/data handling in other parts of the app. 


>And also my PhpShtorm does not see the [id] parameter.

I didn't work with PhpShtorm, so hard to say how to solve it. 

>Question: Is it possible for the required tasks? Sort array elements of slides by custom field?

It's hard to understand what do you mean? You can sort array elements before passing it to `ngx-owl-carousel-o` in a way you want. Just make sure the sorted array is new, not mutated array. 

And my question is: Is the `slide.sort` the same for every slide? If it's the same you'll have errors. Either remove `[id]="slide.sort"` from your code, either provide own different ids with type `string`.

**Comment by YurchenkoAndrew** [comment]
Thanks for the answer. Now I will try. I thought there is a sorting option in ngx-owl-carousel-o itself.

> It's hard to understand what do you mean? You can sort array elements before passing it to ngx-owl-carousel-o in a way you want. Just make sure the sorted array is new, not mutated array.

I can control the transfer of piped data from the backend to the required format. But I just wanted to understand the functionality of the application.

> And my question is: Is the slide.sort the same for every slide? If it's the same you'll have errors. Either remove [id]="slide.sort" from your code, either provide own different ids with type string.

Initially, I thought that sorting is done by the "id" parameter. And accordingly I thought that it is possible to redefine a field from the data table for this parameter.
The values of the "sort" field in the data table are correspondingly different. Although, of course, I would have provided for the possibility of the user entering the same values. Or at least make the values unique.

In the coming days I will try to work with the issue of co-creation.
Thank you again for your answer on this topic.
