### ISSUE TITLE
Does this package SSR with Angular Universal? 

### ISSUE THREAD

**Issue by ElesGergo** [vitalii-andriiovskyi/ngx-owl-carousel-o#131]
Does this package SSR with Angular Universal?

**Comment by blasco** [comment]
I would like if it works with angular universal too, if it does it would be great if they'd add this information to the README

**Comment by vitalii-andriiovskyi** [comment]
@ElesGergo, @blasco, yes it does. 
You don't need to do any configurations to use the carousel within SSR.
