### ISSUE TITLE
 this.carouselService.getInitializedState is not a function

### ISSUE THREAD

**Issue by Luarb** [vitalii-andriiovskyi/ngx-owl-carousel-o#14]
Hello,
After the update I get this error now : 
` this.carouselService.getInitializedState is not a function`

**Comment by Luarb** [comment]
Also I noticed this : 
```
WARNING in ./node_modules/ngx-owl-carousel-o/ngx-owl-carousel-o.ngfactory.js
153:67-72 "export 'ɵx' (imported as 'i1') was not found in 'ngx-owl-carousel-o'

WARNING in ./node_modules/ngx-owl-carousel-o/ngx-owl-carousel-o.ngfactory.js
155:53-58 "export 'ɵx' (imported as 'i1') was not found in 'ngx-owl-carousel-o'

WARNING in ./node_modules/ngx-owl-carousel-o/ngx-owl-carousel-o.ngfactory.js
44:67-72 "export 'ɵx' (imported as 'i1') was not found in 'ngx-owl-carousel-o
```

**Comment by vitalii-andriiovskyi** [comment]
Hello. 
That's strange. I installed lib into new project and everything works fine. Maybe you should remove lib and install it again. 

__Warnings__: did you get them after building your project?

**Comment by Luarb** [comment]
Hello,
Yeah I did what you said, the error is gone.
Thank you !

**Comment by raghvpip3** [comment]
Hey!! @Luarb  how did you get solved it..
