### ISSUE TITLE
How to update carousel after change data?

### ISSUE THREAD

**Issue by yuliagrishchuk** [vitalii-andriiovskyi/ngx-owl-carousel-o#16]
When I add more items for content array, they don't add to owl slides.
How can I refresh my carousel?
Version 1.0.0

**Comment by vitalii-andriiovskyi** [comment]
Version `v1.0.2` solves this downside of the library. 
I suggest to install the latest version of the `ngx-owl-carousel-o` which is `v1.0.7`. 
All versions after `v1.0.0` don't have breaking changes. So the `v1.0.7` should work fine in your project.

Anyway here is the list of changes introduced by all new versions:  [CHANGELOG](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/update-to-v7-of-nrwl-and-angular/CHANGELOG.md)

**Comment by yuliagrishchuk** [comment]
It works on v1.0.7! Thanks!!!!
