### ISSUE TITLE
Ignores end items

### ISSUE THREAD

**Issue by nimishph** [vitalii-andriiovskyi/ngx-owl-carousel-o#161]
Hi @vitalii-andriiovskyi,  I have the following code

```html
<owl-carousel-o [options]="customOptions">
       <ng-template carouselSlide>
               <div *ngFor="let slide of slides">
                      <!-- slide-element-html -->
               </div>
       </ng-template>
</owl-carousel-o>
````

### Using:
   1. Angular 9
   2. Bootstrap 4

<br>
<br>

1.  Case-1:
       - there is a total of 4 slides and the number of items is 4(same)  
       - **Result:** carousel doesn't allow navigation or sliding ( I understand this happens because no. of slides = no. of items)

2.  Case-2:
       - there is a total of 4 slides and the number of items is 3(default) 
       - **Result:** on rendering the carousel renders all four slides but considers only the first 2 slides i.e. it shows only 2 dots, on nav enabled navigates between the 1st and 2nd slides only.

3.  Case-3:
       - there is a total of 4 slides and the number of items is 2
       - **Result:** on rendering the carousel renders all four slides but considers only the first 3 slides with 2 dots and on nav enabled navigates between the 1st 3 slides only.

4. Case-4:
       - total 4 slides and number of items = 1
       - **Result:** it renders and considers all four slides 

Can you please explain if this is a bug or I understood / did something work?

**Comment by vitalii-andriiovskyi** [comment]
Hi @nimishph 

Cases 2-4:

The carousel reads the total number of slides, the value of the option `items`, and then divides total count of slides by the option `items`.  The result is the number of dots, rounded to higher integer number. Dots in this case show how much pages/screens has the carousel. 1st dot navigates to 1st page/screen, 2nd navigates to 2nd page/screen.


2. So in case 2:  
    - You have 4 slides and the option `items: 3`:  
    -  __The Result__: 4/3 = 1.333 which is rounded to 2. You have 2 dots. 

3. In case 3:   
    - 4 slides and 2 items 
    - __The Result__: 4/2 = 2. You have 2 dots. If you had 5 slides for example, you would get 3 dots: 5/2=2.5, rounded to 3.

4. The same in the case 4. 

If you need dots for every item use option `dotsEach`. Set it to `true`.

**Comment by nimishph** [comment]
Ok, got it. Thanks for quick reply
