### ISSUE TITLE
No events to refresh the carousel when there is stage size is changed

### ISSUE THREAD

**Issue by akmalnawfer** [vitalii-andriiovskyi/ngx-owl-carousel-o#162]
I am using "ngx-owl-carousel-o": "~3.0.1", I am trying to reinitialize the slider when the div wrapping the carousel width changes, as far as I went I am unable to refresh or rebuild the carousel by triggering manually like we do in jquery. Is there a way I can trigger refresh?

**Comment by vitalii-andriiovskyi** [comment]
change the length of the array that contains data for slides, or fire the event `resize` on `window`.

**Comment by akmalnawfer** [comment]
> change the length of the array that contains data for slides, or fire the event `resize` on `window`.

this worked. Thank you.

**Comment by akmalnawfer** [comment]
@vitalii-andriiovskyi I'm not sure how I did this, but in angular using window resize event you can manipulate the array that you're using, maybe do a shallow copy of the array or update the array with something.

**Comment by vitalii-andriiovskyi** [comment]
@smlombardi 

1. You need to push or shorten the slides array
```typescript
  refreshCarousel() {
    this.carouselData.push({ id: 'slideId' });
    // or
    this.carouselData.pop();
  }

```
2. Replace any element using object destructuring
```typescript
refreshCarousel() {
    this.carouselData[0] = {...this.carouselData[0]}
  }
```
3. Update options: [refreshing the carousel if options change](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#refreshing-the-carousel-if-options-change)

**Comment by smlombardi** [comment]
Thanks. I am using these options, which work fine except, of course, they don't apply unless you reload the page.

```  
responsive: {
      0: {
        items: 4
      },
      800: {
        items: 4
      },
      1000: {
        items: 5
      },
      1200: {
        items: 6
      }, 
      1400: { 
          items: 7
      }
    },
```
I have several carousels on the page, they get their data from a JSON file.  Isn't there a way I can just force an update for the number of slides without changing my data array?

**Comment by vitalii-andriiovskyi** [comment]
@smlombardi 
The option `responsive` works but keep in mind numbers `0`, `800`, `1000` and so on are not window width. They are th width of the parent DOM element holding the carousel. For example, the screen has the width `1100px` but the carousel occupies only `900px` of the screen. The number of slides will be 4, not 5 as you expect. 

Pay attention to the carousel width across different viewports. 

Also pay attention to the `id` you set to the slide. It has to be string, not number or anything else. https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#setting-custom-slides-ids

**Comment by smlombardi** [comment]
Responsive does indeed work but does not force a redraw at the breakpoint. Resizing the window only shows more or less slides (i.e. crops the carousel).  I need to reload the page in the browser for the right number for the width to kick in.

 I'm just looking for a way to force a redraw on resize, similar to how Netflix does it.

And my enclosing element for each of my carousels is an Angular component the width  of the `body`.

**Comment by vitalii-andriiovskyi** [comment]
@smlombardi 

If you're trying to implement something like this https://www.netflix.com/ua-en/browse/genre/839338 (the first carousel for example), use the option `autoWidth=true`.

add to the code 
```typescript
  @HostListener('window:resize', ['$event']) onResize(event) {
    if (window.innerWidth < 600) {
      this.width = Math.min(300, window.innerWidth * 0.4); 
    } else if (this.width !== 300) {
      this.width = 300;
    }
  }
  width = 300;
```

```html
 
      <owl-carousel-o [options]="customOptions">
        
        <ng-container *ngFor="let item of carouselData">
          <ng-template carouselSlide [id]="item.id" [width]="width">  // your width
            <div class="slider">
              your content
            </div>
          </ng-template>
        </ng-container>
        
      </owl-carousel-o>
```

About `window.innerWidth`: I wrote it simply to express an idea. But it's better to not access `window` directly. You can use this approach https://brianflove.com/2018-01-11/angular-window-provider/

**Comment by smlombardi** [comment]
As you can see, the window is resized, but the number of slides stays the same; they just get cropped and un-cropped.

https://user-images.githubusercontent.com/835148/217638214-6b2bc23c-1906-4263-bfc7-c0b9d1558933.mp4

where as Netflix snaps to a different number of slides at breakpoints as you resize

https://user-images.githubusercontent.com/835148/217639140-14d3ccfc-1a38-4ea4-8031-245d976d2b6b.mp4

**Comment by smlombardi** [comment]
I have tried the various solutions, and still the only way to get the carousel to refresh itself with the correct number of slides it to reload the page.  I have tried this approach, with my normal `items: 5`

```
  @HostListener('window:resize', ['$event'])
  onResize(event) {
    let width: number = window.innerWidth;
    if (width >= 1400) {
      this.updateOptions(6);
    }
  }

  updateOptions(numSlides: number) {
    this.customOptions = { ...this.customOptions, items: numSlides };
  }
```
This does force a re-draw, but I get 6 and a half slides:
<img width="1385" alt="Google Chrome-20230209_140358" src="https://user-images.githubusercontent.com/835148/217913122-d8d779b0-081f-431c-beeb-e3b793ef1fb5.png">

I still have to reload the page itself to update the carousel to look correct:
<img width="1409" alt="Google Chrome-20230209_140723" src="https://user-images.githubusercontent.com/835148/217913330-be9d741a-b857-4636-a94d-63d7e8d21ae3.png">

**Comment by vitalii-andriiovskyi** [comment]
@smlombardi Have tried this way https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#refreshing-the-carousel-if-options-change to change options

**Comment by smlombardi** [comment]
That's exactly where I copied my code from:
```
  updateOptions(numSlides: number) {
    this.customOptions = { ...this.customOptions, items: numSlides };
  }
  ```
As I said, it does indeed "redraw" with 6 slides, but it is askew as in my screenshot.

**Comment by vitalii-andriiovskyi** [comment]
@smlombardi 

Try to use only these options:
```typescript
customOptions: OwlOptions = {
responsive: {
      0: {
        items: 4.2
      },
      800: {
        items: 4.2
      },
      1000: {
        items: 5.2
      },
      1200: {
        items: 6.2
      }, 
      1400: { 
          items: 7.2
      }
    },
    nav: true
}
```

In my testing project everything works and the number of items changes at every breakpoint. I don't use `autoWidth` and `width` property

**Comment by smlombardi** [comment]
my code does seem to work in a bare-bones stackblitz: https://stackblitz.com/edit/angular-ivy-y6qpy4?file=src/app/carousel-section/carousel-section.component.html

So now I need to figure out what other code in my real app is interfering with it. Possibly one of the various CSS files our app is using
```
            "styles": [
              "node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/prismjs/themes/prism-coy.css",
              "node_modules/primeicons/primeicons.css",
              "node_modules/font-awesome/css/font-awesome.min.css",
              "node_modules/@ng-select/ng-select/themes/default.theme.css",
              "node_modules/ngx-toastr/toastr.css",
              "node_modules/shepherd.js/dist/css/shepherd.css",
              "node_modules/ngx-owl-carousel-o/lib/styles/prebuilt-themes/owl.carousel.min.css",
              "node_modules/ngx-owl-carousel-o/lib/styles/prebuilt-themes/owl.theme.default.min.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.snow.css",
              "src/sass/designsystem/designsystem.scss",
              "src/styles.scss"
            ],
            ```
