### ISSUE TITLE
Hide prev and next button

### ISSUE THREAD

**Issue by shobhitvaish** [vitalii-andriiovskyi/ngx-owl-carousel-o#17]
Thanks for the great library!

I am trying to hide prev and next button but no luck so far.
If I set **nav** to false then it won't let me use my custom prev and next button i.e. owlCar.prev() and owlCar.next() has no effect after setting  **nav** to false. Am I missing something, kindly help.

Thanks!

**Comment by vitalii-andriiovskyi** [comment]
Hi!

I blocked methods `owlCar.prev()` and `owlCar.next()` for the case when the option `nav` is set to `false`. The reason of this was if the navigation isn't needed, these methods must do no job. However,  now I see these two may be needed. 

Anyway, there'll be a small update of the library within a day and I'll unblock these methods in new version. 
I'll notify when the new version will be published.

**Comment by shobhitvaish** [comment]
Great, Thanks!

**Comment by vitalii-andriiovskyi** [comment]
The new version `v1.0.8` is published. Methods `owlCar.prev()` and `owlCar.next()` are unblocked.

**Comment by shobhitvaish** [comment]
That was quick :)

Thanks again!
