### ISSUE TITLE
Stopped autoplay starts if responsive fires

### ISSUE THREAD

**Issue by MoonLoq** [vitalii-andriiovskyi/ngx-owl-carousel-o#170]
Angular 10, NgxOwlCarouselO 4.1.0.
Bug with autoplay and responsive - if manually stop autoplay with method stopAutoplay(), autoplay start again if responsive fires on screen width changing.

**Comment by vitalii-andriiovskyi** [comment]
Hi @MoonLoq 

Fixed. Install version v.4.1.1
