### ISSUE TITLE
stagePadding not working inside responsive object

### ISSUE THREAD

**Issue by shobhitvaish** [vitalii-andriiovskyi/ngx-owl-carousel-o#18]
Hi,

I would like to set stagePadding based on width so I need to set it in the responsive object but that doesn't seem to have any effect. Here is my config

`{
      loop: true,
      responsive: {
        0: {
          items: 3,
          stagePadding: 30
        },
        210 : {
          items: 2,
          stagePadding: 20
        },
        254 : {
          items: 2,
          stagePadding: 50
        },
        418: {
          items: 5,
          stagePadding: 50
        },
        1000: {
          items: 6,
          stagePadding: 50
        }
      },
      dots: false,
      navSpeed: 1100,
      mouseDrag: true,
      touchDrag: true,
      pullDrag: true,
      nav: false
    };`

Am I missing something?

**Comment by vitalii-andriiovskyi** [comment]
Hi,

For now, `ngx-owl-carousel-o` handles just the option `items` in the responsive object. I'll add the support for other options within a day.

**Comment by shobhitvaish** [comment]
Thanks!
