### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by chuhancheng** [vitalii-andriiovskyi/ngx-owl-carousel-o#183]
Since our project upgrade to angular 13. Jest test will report `Unexpected value 'CarouselModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.`

**Comment by ingeJulianLasso** [comment]
Yes please add support for Angular 13

**Comment by vitalii-andriiovskyi** [comment]
@chuhancheng @ingeJulianLasso 

Added supporrt for Angular 13. Install v7.0.0

**Comment by ingeJulianLasso** [comment]
@vitalii-andriiovskyi  thank you very much, I will test it later and if any eventuality, I will be communicating it.

Again, thank you very much for your collaboration.
