### ISSUE TITLE
Angular does not get 'stable' when using autoplay

### ISSUE THREAD

**Issue by pappkamerad** [vitalii-andriiovskyi/ngx-owl-carousel-o#187]
As the autoplay feature is using `setTimeout`, Angular will never get 'stable' when it is enabled (ApplicationRef.isStable).

For more info see https://angular.io/api/core/ApplicationRef#isstable-examples-and-caveats

This is a problem for us, as we rely on the stable flag for numerous functionality, like scroll restoration and tracking. It can also be an issue for server-side rendering, as this waits for `isStable` as well.

**Comment by pappkamerad** [comment]
I opened a PR with a fix

**Comment by vitalii-andriiovskyi** [comment]
Hi @pappkamerad 
thanks for the improvement of the library. 

What version of `ngx-owl-carousel-o` do you use? So I could know what version to test with your solution.

**Comment by pappkamerad** [comment]
we currently use 6.0.0

**Comment by vitalii-andriiovskyi** [comment]
@pappkamerad 

I published updated version with the fix. Update the package to v6.0.2

**Comment by pappkamerad** [comment]
thanks! :+1: 

will it be released for 7.0.0 as well?

**Comment by vitalii-andriiovskyi** [comment]
@pappkamerad It's already done. `v7.0.1`

**Comment by pappkamerad** [comment]
ah, great thx :)
