### ISSUE TITLE
Why owl-carousel.js doesn't have to install global?

### ISSUE THREAD

**Issue by rainstormza** [vitalii-andriiovskyi/ngx-owl-carousel-o#2]
Why owl-carousel.js doesn't have to install global?
I look in your source code but I don't see any owl-carousel.js, so I am just curious why I don't have to install owl-carousel.js before use this lib.

thanks.

**Comment by vitalii-andriiovskyi** [comment]
The library `ngx-owl-carousel-o` is written for the framework _Angular 6_. It follows the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#). The package has 5 versions of the library and the module bundler [Webpack](https://webpack.js.org/) chooses the needed one. There's no `owl-carousel.js`. Each version has its prime file. It can be `index.js` or `index.d.ts` or `ngx-owl-carousel-o,js`. You can use this library just in Angular project. 

You have to intall this library before using it. You can do it by running `yarn add ngx-owl-carousel-o` or `npm install ngx-owl-carousel-o` in the command line (cmd for Windows or Terminal for Macs). First command requires Node.js and Yarn installed on your PC. Second one demands just Node.js. 
The loaded library is the folder `node_modules`. Installing and using `ngx-owl-carousel-o` is described in [documentation](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/tree/develop/ngx-owl-carousel-o). 

Maybe you need this [Owl Carousel](https://owlcarousel2.github.io/OwlCarousel2/)

**Comment by rainstormza** [comment]
As I understand this lib has the feature as owl-carousel2.
https://owlcarousel2.github.io/OwlCarousel2/docs/started-welcome.html

Am I right?

thanks @vitalii-andriiovskyi

**Comment by vitalii-andriiovskyi** [comment]
Yes, you're right. However, some of the features aren't realized in this lib. They are mentioned in the documentation.
