### ISSUE TITLE
Make "Angular Router" dependency optional

### ISSUE THREAD

**Issue by nazar-kuzo** [vitalii-andriiovskyi/ngx-owl-carousel-o#20]
Hi,

Thanks for your effort porting owl carousel to Angular!
I would like to ask you to mark all the injection tokens: [ ActivatedRoute, Router ] as @Optional
since it forces application to use "Angular Router" library even if it is not used in any case (like mine).

Also there exists dependency on "RouterModule" inside of "CarouselModule" that also should be revisited.

**Comment by vitalii-andriiovskyi** [comment]
Hi.

`ActivatedRoute` and `Router` are injected using `@Optional` decorator. Also, `RouterModule` is removed from `CarouselModule`. Now it should work in your case. Please, update the lib to version `v1.0.11`.
