### ISSUE TITLE
[WARNING] Expected identifier but found "*"

### ISSUE THREAD

**Issue by Talb2005** [vitalii-andriiovskyi/ngx-owl-carousel-o#201]
When creating production build (Angular 13.2.0), a warning appears: 
`Warning: ▲ [WARNING] Expected identifier but found "*"
    styles.dab7755014ab7e5f.css:207:2:
      207 │   *display: inline;`

I've found this `*display: inline;` in a few css files: 

- ngx-owl-carousel-o/lib/styles/scss/_theme.scss
- libs/ngx-owl-carousel-o/src/lib/styles/scss/_theme.scss
- ngx-owl-carousel-o/lib/styles/prebuilt-themes/owl.theme.default.css
- libs/ngx-owl-carousel-o/src/lib/styles/prebuilt-themes/owl.theme.default.css
- ngx-owl-carousel-o/lib/styles/prebuilt-themes/owl.theme.green.css
- libs/ngx-owl-carousel-o/src/lib/styles/prebuilt-themes/owl.theme.green.css

**Comment by vitalii-andriiovskyi** [comment]
@Talb2005 

Your solution to remove `*` is a little bit incorrect, cause it rewrites css-rules. I removed lines with `*display` and published version `7.0.2`. This version is for Angular 13
