### ISSUE TITLE
Infinite loop and browser tab freeze with non-integer # of items to display and few items in carousel

### ISSUE THREAD

**Issue by pappgergely** [vitalii-andriiovskyi/ngx-owl-carousel-o#213]
We are using ngx-owl-carousel-o in our e-commerce solution, and it's a charm. However, there is a special case when it freezes the browser completely by getting into an infinite loop.

I have created this stackblitz example to show the case (this is safe to open yet): https://stackblitz.com/edit/angular-ivy-zno3fe
Nothing special, 7 items in the carousel, and showing 2.25 items (so 2 and a "bit of the next") – which is a requirement from the design.

However, when you set the items from 2.25 to 4.25, OR delete 3 items from the 7 (so only 4 remains in the carousel – use the products[] in the app.component), the whole iframe freezes in stackblitz. (If you open the preview in a separate window, you have to close the whole browser tab.)

I have traced the bug down, and it seems to be in the carousel.service's run() function
It currently says:  `while (repeat--) {`
If I change it to  `while (repeat-- > 0) {`
the problem goes away. I could try this only in my node_modules/ngx-owl-carousel-o/fesm2015/ngx-owl-carousel-o.mjs file, which is built into the app, but seems to solve the problem.

Sorry, but NX is above my head, so I don't want to issue a pull req that's gonna probably be rejected... but could you please have a quick look on this?

**Comment by denniskeithgaso** [comment]
I also have the same issue. Some owl carousel implementation will accept decimals for items, but in other cases it will fall in to infinite loop and becomes unresponsive.

**Comment by vitalii-andriiovskyi** [comment]
@pappgergely 

Fixed and published new version. Upgrade please to the version 7.0.3
