### ISSUE TITLE
carousel items gets shrinked or expand in prod. build.

### ISSUE THREAD

**Issue by Gauravdarkslayer** [vitalii-andriiovskyi/ngx-owl-carousel-o#214]
Hello @vitalii-andriiovskyi ,  I am using ngx-owl-carousel-o ^7.0.1
with angular version 13.1.2
The carousel works absolutely fine in the local server but after production build, it behaves very abnormally.
 This is the expected output
![image](https://user-images.githubusercontent.com/18503497/157095947-d7be0484-40e4-4356-85b9-1f0f7c5a6a6b.png)

![image](https://user-images.githubusercontent.com/18503497/157096190-fa2225a2-605a-4c1e-8428-8c6ee1d8ce2c.png)(Sometimes after a refresh items get collapsed)

![image](https://user-images.githubusercontent.com/18503497/157095712-31f896e0-83ab-44f4-b337-0302dd22ea02.png)
(And here it expands after a refresh)

These cases are random

actually the width of .owl-item becomes 574px in image 3 and 74px in image 2.

let me know if more details are needed. Thank you

**Comment by vitalii-andriiovskyi** [comment]
@Gauravdarkslayer 

It looks like you define the width of every slide dynamicly and use the option `autoWidth`. I think you should check how the width of slides gets calculated. 

To find the solution, I need more details, to be able to reproduce your issue.

**Comment by Gauravdarkslayer** [comment]
@vitalii-andriiovskyi Yeah that totally works fine, after adding autoWidth: true and that @Input property with fixed width. Thanks for a quick response.
