### ISSUE TITLE
startPosition is not working

### ISSUE THREAD

**Issue by abhasbaghel** [vitalii-andriiovskyi/ngx-owl-carousel-o#22]
Hello,

I need to set startPosition of specific slide but it is not working.
The possible root cause is **strict comparison** in below line of code "return slide.id === cache.current;"

 filter: ['width', 'items', 'settings'],
                run: function (cache) {
                    /** @type {?} */
                    var current = cache.current ? _this.slidesData.findIndex(function (slide) { **return slide.id === cache.current;** }) : 0;
                    current = Math.max(_this.minimum(), Math.min(_this.maximum(), current));
                    _this.reset(current);
                }

**Please check and help me to get it resolved my issue.**

**Comment by vitalii-andriiovskyi** [comment]
Hi, 

this is strange. The option `startPosition` works correctly. 
Can you supply details about your case?

**Comment by abhasbaghel** [comment]
Hi Vitalii,
Thanks a ton for your reply.

I am using this carousel in a simple way.

Below is my code. Also I have attached two images that is SS of browser console. The **Bug.jpg** is your code and **Correct.jpg** is taken when I changed the code. You can easily find the differences after removing **strict comparison**  (===).

Please check my code below

**// HTML Code Start //**

<owl-carousel-o [options]="customOptions" #owlCar>
  <ng-container *ngFor="let item of items?.steps;trackBy: $index;let i = index">
	  <ng-template carouselSlide [id]="i">
		  <div [class]="mapGroupName(item.groupID,item.status)">
			  <i class="statusIcon"></i>
			  <input type="button" class="inner-btn-icons vpc" [class]="mapClassName(item.keyName)">
			  <span class="list-group-item-heading" [class]="mapGroupName(item.groupID,'no')" title="{{item.title}}">{{item.title}}</span>
			  
		  </div>
	  </ng-template>
  </ng-container>
</owl-carousel-o>

**// HTML Code End//**

**// Angular Code Start//**

customOptions: any = {
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    dots: false,
    navSpeed: 700,
    loop:false,
    rewind:false,
    navText: ["<i class='carousel-control-prev-icon'></i>", "<i class='carousel-control-next-icon'></i>"],
    nav: true,
    startPosition: 7,
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 6
      },
      740: {
        items: 7
      },
      940: {
        items: 9
      }
    }
  }
  activeSlides: SlidesOutputData;
  slidesStore: any[];
  @ViewChild('owlCar') owlCar;
  
  getDataJ(serviceUrl):Observable<any>{
        return this.http.get(serviceUrl,this.getHeaderOfApplication())
        .pipe(
            map(response => response),
            retry(0),
            catchError(this.customerrorHandler)
        )
      }
  
  getDataFromJSON(serviceUrl){
        this.getDataJ(serviceUrl).subscribe(
            (data) => {
              if (data && data.steps.length != 0) {
                this.items = data;
              } else {
                console.log('Steps not found');
              }
              
            },
            (error) => console.log(error)
          )
      }
  
  ngOnInit() {
     this.getDataFromJSON('assets/data/dummy.json');
  }

**// Angular Code End//**

**Please check and help me to fix this issue. I have been stuck since long time.
![bug](https://user-images.githubusercontent.com/7964938/53826571-e02dee80-3f9e-11e9-95b6-b30e4ebf5076.jpg)
![correct](https://user-images.githubusercontent.com/7964938/53826583-ecb24700-3f9e-11e9-89fc-33cacc5f5c6f.jpg)

**

**Comment by vitalii-andriiovskyi** [comment]
In your case all `id`s have the type `number`. But the library expects `id`s which have the type `string`
Your code is:
``` html
<ng-template carouselSlide [id]="i">
```

Possible solution is `[id]="'' + i"` not the `[id]="i"`:
``` html
<ng-template carouselSlide [id]="'' + i">
```

Also, if you don't use the `id`s of the slides in your code, you can remove `[id]`. The library will generate default `id`s.

**Comment by abhasbaghel** [comment]
Oh Great vitalii ! I was not thinking like that.

It solve my issue. Thank you so much.
