### ISSUE TITLE
No Slides to Show

### ISSUE THREAD

**Issue by tnohelty** [vitalii-andriiovskyi/ngx-owl-carousel-o#222]
I get the Warning: "There are no slides to show. So the carousel won't be re-rendered" 2 times on the console followed by the Warning: Option 'items' in your options is equal to the number of slides. So the navigation got disabled.  I have checked using the "initialized" event and there are 4 slides loaded and the option items is set to 1.  The responsive array is set to 4.  The display of the page seems to work just fine.  One thing that may be normal, but I have loop set to true and the display continues to move the slide items to the left one at a time.  So I am wondering why these warnings are displayed.  Assuming the second warning is accurate, I am also confused as why the looping continues (unless navigation means the arrows that i have defined that are not showing).  I think I just need an explanation as to what these warnings are telling me.  Thanks

**Comment by vitalii-andriiovskyi** [comment]
It's fixed within the issue https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/issues/93
