### ISSUE TITLE
Not working with Angular v14.0.6

### ISSUE THREAD

**Issue by faraz-ahmad** [vitalii-andriiovskyi/ngx-owl-carousel-o#223]
<img width="1030" alt="Screenshot 2022-07-18 at 6 45 12 PM" src="https://user-images.githubusercontent.com/3992738/179519546-2050818c-dffa-4d17-baa1-f029bbb56dbd.png">

Here is my configuration:
<img width="777" alt="1" src="https://user-images.githubusercontent.com/3992738/179520253-20ae8b01-2f3f-4ccc-abbf-3d6698639c65.png">

<img width="527" alt="2" src="https://user-images.githubusercontent.com/3992738/179520283-3b64498e-453b-453a-a5bd-794e2ba8692c.png">

Angular CLI: 14.0.6

@vitalii-andriiovskyi  I tried a fresh project with the same Angular CLI version and getting the same error.

**Comment by vitalii-andriiovskyi** [comment]
@faraz-ahmad 

Replace `~ngx-owl-carousel-o` with `node_modules/ngx-owl-carousel-o` for now.

**Comment by faraz-ahmad** [comment]
> @faraz-ahmad
> 
> Replace `~ngx-owl-carousel-o` with `node_modules/ngx-owl-carousel-o` for now.

Thanks @vitalii-andriiovskyi. It resolved the issue.

Although It is not the right approach to include node_modules in the path. Can you please confirm when It will be fixed permanently without modifying the path.

**Comment by vitalii-andriiovskyi** [comment]
@faraz-ahmad 

yes, sure

**Comment by faraz-ahmad** [comment]
> @faraz-ahmad
> 
> yes, sure

@vitalii-andriiovskyi  Have you fixed this issue?

**Comment by vitalii-andriiovskyi** [comment]
@faraz-ahmad 

The issue is fixed. Update `ngx-owl-carousel-o` to `14.0.1`

**Comment by faraz-ahmad** [comment]
This has been fixed now. Thank you.
