### ISSUE TITLE
Avoid startPosition becoming 0 when datasource is uploaded

### ISSUE THREAD

**Issue by stefano-frigerio** [vitalii-andriiovskyi/ngx-owl-carousel-o#225]
Hi I'm developing a lazyload carousel. When i get near the end of the carousel I make a call to backend to push new elements inside array used for carousel, but when this happens Carousel active element goes back to the first one. 
I tried using [id] to set the position back to previous active element and it works, but the carousel is scrolling to that position so it seems like a glitch. How can I make the element focused stay focused even if I add elements to array? (position of element doesn't change in array, I only make a push of new elements)
Thank you

**Comment by vitalii-andriiovskyi** [comment]
@stefano-frigerio 

Define `startPosition` at  the moment you add extra slides and update the option `startPosition` while adding extra slides.
To find out `startPosition` use event `translated` or `change` https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#events

**Comment by stefano-frigerio** [comment]
Hi @vitalii-andriiovskyi I tried what you suggested and successfully set startPosition when pushing element into array, but the carousel keeps going back to first slide

**Comment by vitalii-andriiovskyi** [comment]
@stefano-frigerio 

are you setting `startPosition` as it is described here: https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#refreshing-the-carousel-if-options-change ?

**Comment by stefano-frigerio** [comment]
I tried everything, but probably I'm missing something. I even tried this example https://stackblitz.com/edit/ngx-owl-carousel-o?file=src%2Fapp%2Fapp.component.ts changing loop and autoplay to false and setting startPosition to a number different from 0, but it's always starting from slide 0, I don't get why.

**Comment by vitalii-andriiovskyi** [comment]
@stefano-frigerio 

Here is working example https://stackblitz.com/edit/ngx-owl-carousel-o-j31ky4
Take into account that this example uses `ngx-owl-carousel-o@2.0.3`, Angular 8.
This version doesn't have the ability to catch changes in options and rerender. It works cause rerendering was initiated by the change in `this.apiData` and options updation happend before it. 

Starting from the version `v5.1.1`, the library is able to catch changes in options and rerender itself. 
Also `[id]` of a slide must be string.

**Comment by vitalii-andriiovskyi** [comment]
Clothing the issue due to inactivity. If needed reopen it.
