### ISSUE TITLE
Won't load at first

### ISSUE THREAD

**Issue by Shalil-j** [vitalii-andriiovskyi/ngx-owl-carousel-o#233]
at first, it only shows the nav, if I don't interact, the content of the carousel won't show up until I click or click-drag mouse over it in angular CLI 14.2v. Even if I'm having multiple carousels on the same page, I have to manually click all to work

**Comment by vitalii-andriiovskyi** [comment]
@Shalil-j 
Please, share example to reproduce the issue.

**Comment by Shalil-j** [comment]
actually, i forget to add browser-animation module to module.ts in angular
