### ISSUE TITLE
No translate started event with direction and/or next index

### ISSUE THREAD

**Issue by craxrev** [vitalii-andriiovskyi/ngx-owl-carousel-o#25]
Is there an event which triggers when translate starts? i.e. when drag is finished

I know there is the `translated` event but it triggers when translate is finished (after the animation), I need to start an animation when the mouse is released when dragging.

I've tried using the `change` event, but I couldn't find how to get the next slide index or at least the direction the slide is going (`SlidesOutputData.startPosition` is always pointing to the current slide).

I found no possible way or am I missing something?

**Comment by vitalii-andriiovskyi** [comment]
Hi, @craxrev!
Sorry for the late answer. 

> I found no possible way or am I missing something?

You didn't miss anything. That's how it works. The event `change` fires at the moment when the changes start and of course, there's no actual data about new active slides.

I added a new event `changed` which passes data about new active slides. So, `SlidesOutputData.startPosition` points to new start position. Check, please, if it's good for your case.

The usage of this event is the same as the usage of `change`.

**Comment by craxrev** [comment]
Hey @vitalii-andriiovskyi thank you for getting back to me!

Yeah I'll look into it tonight 👍
