### ISSUE TITLE
[Question] How can I style the .active.center slide from Ngx Owl Carousel in Angular?

### ISSUE THREAD

**Issue by HorselessName** [vitalii-andriiovskyi/ngx-owl-carousel-o#259]
Hello!

I am facing a issue where I cannot style and apply custom styles to the slides with `.active.center` classes.

The Owl Carousel is working correctly, but when I try to style the component using the classes that are generated by `<ng-template carouselSlide>` nothing changes...

Can someone help me?

**Comment by vitalii-andriiovskyi** [comment]
@HorselessName 

If you try to overwrite the library styles in a component styles, try to use `::ng-deep`.
