### ISSUE TITLE
Changing carousel options after setup

### ISSUE THREAD

**Issue by xxl2damax** [vitalii-andriiovskyi/ngx-owl-carousel-o#27]
I'm having trouble changing the options of the owl carousel after the setup. Any update i make to the options doesn't seem to change anything.

The code i have tried 

`
@ViewChild('owl') owl: CarouselComponent; `
`.....`
`this.owl.options.mouseDrag = false; (initial is true)`
`this.owl.options = {mouseDrag: false, ...}`

**Comment by vitalii-andriiovskyi** [comment]
Hi @xxl2damax.

The code doesn't allow to change settings after they are set. You have the option `responsive` for different screens.

**Comment by xxl2damax** [comment]
@vitalii-andriiovskyi thanks for the reply.

However, i took a peek at the carousel source code and managed to find a workaround for what i wanted.

To disable the carousel mouseDragging (after initial setup) i can mess with owlDOMData  object in CarouselComponent.

`this.owl.owlDOMData.isMouseDragable = false` did the trick :)

**Comment by lifehappensoutdoors** [comment]
Is it possible to block the touchDrag/mouseDrag in a specific direction?

**Comment by vitalii-andriiovskyi** [comment]
Hi @lifehappensoutdoors.

No, it's impossible to block the `touchDrag/mouseDrag` in a specific direction. You can just switch off or switch on the `touchDrag/mouseDrag`.

**Comment by lifehappensoutdoors** [comment]
Hello @vitalii-andriiovskyi, can I please have some directions about how the touchDrag/mouseDrag is implemented so maybe i can have my workaround to block it in a specific direction

**Comment by vitalii-andriiovskyi** [comment]
Hi @lifehappensoutdoors 

Main logic is in the code in the file [libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts). Additional methods are in the file [libs/ngx-owl-carousel-o/src/lib/services/carousel.service.ts](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/services/carousel.service.ts).

The algorithm is this:
1. When the event `mousedown` or `touchstart` fires the method [_onDragStart()](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts#L207) gets called. 
    Its main job is saving coords of the mouse pointer or touch and attaching handlers to the events `mousemove`, `touchmove`, `mouseup` and `touchend`. 
2. The handler to events `mousemove` and `touchmove` is [_oneMouseTouchMove()](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts#L236). It watches whether the user has dragged the carousel 3px more from the starting position. If so this handler gets detached and another method [bindOnDragMove](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts#L188) is attached.
  The object [`delta`](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/stage/stage.component.ts#L241) contains 3px or another number of px. If `delta.x < 0 ` then you're dragging to the right hand side, if `delta.x > 0 ` then you're dragging to the left hand side.

**Comment by lifehappensoutdoors** [comment]
thank you @vitalii-andriiovskyi
