### ISSUE TITLE
Angular 18

### ISSUE THREAD

**Issue by ant-ia** [vitalii-andriiovskyi/ngx-owl-carousel-o#278]
Hi @vitalii-andriiovskyi 
will you also support angular 18?

thank you so much for your work

**Comment by vitalii-andriiovskyi** [comment]
@alexandresebrao Will do within 2-3 days

**Comment by alexandresebrao** [comment]
Thank you @vitalii-andriiovskyi!!!

**Comment by vitalii-andriiovskyi** [comment]
@alexandresebrao @ant-ia Published `v18.0.0`

**Comment by ant-ia** [comment]
HI @vitalii-andriiovskyi , 
thank u so much for your support.
