### ISSUE TITLE
owl-dots <span>null</span> in Edge Browser

### ISSUE THREAD

**Issue by rankitbishnoi** [vitalii-andriiovskyi/ngx-owl-carousel-o#28]
In Edge Browser the owl-dots are shown with null written behind them. The null is written in span tag. it is not happening in chrome.

`\<div class="owl-dot active ng-star-inserted" _ngcontent-c5="">
     <span _ngcontent-c5="">null</span>
\</div>"`

**Comment by vitalii-andriiovskyi** [comment]
Hi, @rankitbishnoi 

Sorry for the late answer. This problem is solved. I published new version of the lib: `v1.1.2`. Download it, please
