### ISSUE TITLE
Support for Angular 19

### ISSUE THREAD

**Issue by alexandresebrao** [vitalii-andriiovskyi/ngx-owl-carousel-o#283]
Hello, any plans on supporting angular 19 soon.

I think I'm the guy that is always asking for release support :+1: 

Thank you in advance

**Comment by iamishver** [comment]
Any update on Angular 19?

**Comment by danailov-z** [comment]
+1

**Comment by vitalii-andriiovskyi** [comment]
@danailov-z @alexandresebrao @iamishver 
Upgraded. Thanks for patience)
