### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by ginestonit** [vitalii-andriiovskyi/ngx-owl-carousel-o#29]
**first :** 
great product ! 
lazyLoad didn't work with ngx-owl-carousel so ngx-owl-carousel-o is the solution !!

**The problem :**
> when I use you ngx-owl-carousel-o inside classic bootstrap row it works
> when I use the same code into a **modal** the pictures don't appear
When I resize the window the picture appear.
So I send a resize event ... in ngAfterviewinit method. It works but that's not a good solution.

At the moment I still use ngx-owl-carousel-o because this is a good solution for lazyLoad option.
But if I could use modal it would be great.
(I need modal because it's a good solution to display fullscreen image on smartphones)

**Comment by vitalii-andriiovskyi** [comment]
Hi @ginestonit.
Sorry for late answer.

What do you use to show the carousel in the modal? I mean plugin or library.

**Comment by ginestonit** [comment]
Hi,

Just a simple boostrap4 modal with ngx-owl-carousel-o inside.

<div class="modal-dialog modal-lg">
...
<div class="modal-body>
and inside when I use <owl-carousel-o> the content doesn t appear except
when I resize the window.

No problem for the late answer 😉

**Comment by vitalii-andriiovskyi** [comment]
The problem of not showing the picture of the carousel in modal is that:

the width of DOM-element `div.owl-stage` is 0 and the picture also takes this width. The width of `div.owl-stage` is evaluated using the width of `div.owl-carousel` which gets known on the initializing of the carousel.

**Comment by ginestonit** [comment]
Thanks a lot.
I will try your solution as soon as possible.

**Comment by ginestonit** [comment]
Test done :+1:  I confirm your solution 2 works with ngx-bootstrap.
Thank you very much!
