### ISSUE TITLE
Carousel with Grid-Layout

### ISSUE THREAD

**Issue by Swesson92** [vitalii-andriiovskyi/ngx-owl-carousel-o#31]
Having difficulties implementing Grid with the carousel, any suggestions or reasons why it wont work? 
Check out my stackoverflow issue : https://stackoverflow.com/questions/56106891/grid-layout-for-owl-carousel

**Comment by vitalii-andriiovskyi** [comment]
Hi @Swesson92.

Sorry for the late answer. You can see it on [https://stackoverflow.com/questions/56106891/grid-layout-for-owl-carousel](https://stackoverflow.com/questions/56106891/grid-layout-for-owl-carousel)
