### ISSUE TITLE
Export OwlOptions in public_api

### ISSUE THREAD

**Issue by nkovacic** [vitalii-andriiovskyi/ngx-owl-carousel-o#33]
Could OwlOptions be exported in public_api so that `import { OwlOptions } from 'ngx-owl-carousel-o'` could be possible?

Currently this is only possible with  `import { OwlOptions } from 'ngx-owl-carousel-o/lib/models/owl-options.model'`...

**Comment by vitalii-andriiovskyi** [comment]
Hi @nkovacic.

The export of `OwlOptions` is added to `public_api.ts`. I published new version `v1.1.4`. Please, install it.
