### ISSUE TITLE
How to manage item count when single result occurs

### ISSUE THREAD

**Issue by karthickms** [vitalii-andriiovskyi/ngx-owl-carousel-o#36]
If item count is 3, result of the application count is one, it will displays as full view

**Type script:**
`
	similar_listOptions: any = {
		loop: false,
		mouseDrag: true,
		touchDrag: true,
		pullDrag: true,
		dots: false,
		navSpeed: 700,
		margin: 20,
		navText: ['<i class="fa fa-angle-left" aria-hidden="true"></i>', '<i class="fa fa-angle-right" aria-hidden="true"></i>'],
		responsive: {
		  0: {
		    items: 1
		  },
		  400: {
		    items: 1
		  },
		  600: {
		    items: 2
		  },
		  940: {
		    items: 3
		  }
		},
		nav: true
	}`

`
				<owl-carousel-o [options]="similar_listOptions" class="owl-slider">
				    <ng-container *ngFor="let similarlist_image of similarlist_images">
				      <ng-template carouselSlide [id]="similarlist_image.id">
				      	<a routerLink="/sample/{{similarlist_image.id}}" class="d-block color-inherit">
					        <img [src]="similarlist_image.photo_id.list_photo">
					    </a>
				      </ng-template>
			      	</ng-container>
			  	</owl-carousel-o>`

Thanks in advance

**Comment by vitalii-andriiovskyi** [comment]
Hi @karthickms.
This behavior is by default. If your `similarlist_images` contains 1 item, the value of the option `items` will always be skipped to `1` and the slide will take the same width as the carousel has. There's no way to change this behavior.

You can set the `max-width` of the `<a ...` and align it using `margin` or 
add 2 empty items to `similarlist_images` which will add 2 slides. 

By the way: read this please: [Tag `a` in the slide. Directive `owlRouterLink`](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#owlRouterLink)

**Comment by karthickms** [comment]
Yes @vitalii-andriiovskyi . I have set the max-width to the <a> tag. And thanks for given the Directive information.
