### ISSUE TITLE
unsubscribe on destroy event

### ISSUE THREAD

**Issue by hooloom** [vitalii-andriiovskyi/ngx-owl-carousel-o#38]
there is an issue with ngx-owl-carousel.js located in fesm2015 folder.
in angular onDestory you are not allowing enough time if component is called from inside a directive or another component - it's a simple fix as denoted below.  Please update.
` ngOnDestroy() {
        if (this.resizeSubscription) {
            this.resizeSubscription.unsubscribe();
        }
        if(this._slidesChangesSubscription){
        this._slidesChangesSubscription.unsubscribe();
        }
        if (this._allObservSubscription){
        this._allObservSubscription.unsubscribe();
        }
    }`

original file
` ngOnDestroy() {
        if (this.resizeSubscription) {
            this.resizeSubscription.unsubscribe();
        }
      
        this._slidesChangesSubscription.unsubscribe();
        
     
        this._allObservSubscription.unsubscribe();
        
    }`

**Comment by vitalii-andriiovskyi** [comment]
Hi @hooloom.

Thanks for pointing out the issue and giving the solution. The library is updated.   
The latest version for Angular 8 is v2.0.1.  
The latest version for Angular 7 is v1.1.7.
