### ISSUE TITLE
How to enable small thumbnail ?

### ISSUE THREAD

**Issue by Santoshah** [vitalii-andriiovskyi/ngx-owl-carousel-o#40]
The big slider 1 item page screen is working fine but I would like to have a small thumbnail at bottom so when I click on that thumbnail it goes to specific image.

How can I do this ? 

```<div class="carousel-container" #owlElement1>
    <owl-carousel [options]="owlConfig" [items]="bannerList" [carouselClasses]="['bannerList','owl-theme', 'row', 'sliding']">
        <div class="item banner-items" *ngFor="let item of bannerList">
             <app-banners></app-banners>
        </div>
    </owl-carousel>
</div>```

`@ViewChild('owlElement1', {static: true}) owlElement: OwlCarousel
  bannerList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  owlConfig = {
    items: 1,
    dots: false,
    nav: true,
  }`

**Comment by vitalii-andriiovskyi** [comment]
Hi, @Santoshah .

Investigate this [Doubled Carousel](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/tree/develop/apps/demo-owl-carousel/src/app/doubled-carousel/doubled-carousel), please. This is an example of creating 2 carousels. The first one shows just one big image, the second one contains thumbs for managing the first carousel. 

Key points are:
1. It's needed to supply own `id`s to the slides. `id`s must have the type of `strings`. Id of big image and thumbnail must be the same.
2. Use template reference variable (e.g. `#owlCar`) to get and manage the carousel with one big image ( `owlCar.to('id-of-the-needed-slide')` ).

You can clone the project and run the app with doubled carousel. To make the second step use the command `ng serve`.

**Comment by Santoshah** [comment]
Great @vitalii-andriiovskyi Thanks it worked...
