### ISSUE TITLE
Firefox issue for full width banner

### ISSUE THREAD

**Issue by Santoshah** [vitalii-andriiovskyi/ngx-owl-carousel-o#41]
It is scaling the whole site. The no. of banner available on the page it is adding horizontal scrollbar all the way to the last banner. How do I fixed that ?

**Comment by vitalii-andriiovskyi** [comment]
Hi @Santoshah, 

Please provide details of using the `ngx-owl-carousel-o` in your case, so I could to reproduce the issue and investigate it.

**Comment by Santoshah** [comment]
Below is the code I am using. Same code work perfectly fine for chrome. Not sure why it is showing strange behavior in Firefox. 

I have look closely to this issue on firefox. It looks like the item which is suppose to be 1517. The width keep increasing by 1 more digits. That is really a strange issue.

I have 10 banner slide repeating.

screenshot of firefox
http://prntscr.com/p3qu4z




``` 
import { OwlCarousel } from 'ngx-owl-carousel';

 @ViewChild('owlElement1', {static: true}) owlElement: OwlCarousel
  bannerList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  owlConfig = {
    items: 1,
    dots: false,
    nav: true,
  }```

```<div class="carousel-container homepageBanners" #owlElement>
    <owl-carousel [options]="owlConfig" [items]="bannerList" [carouselClasses]="['bannerList','owl-theme', 'row', 'sliding']">
        <div class="item banner-items" *ngFor="let item of bannerList">
             <app-banners></app-banners>
        </div>
    </owl-carousel>
</div>```

**Comment by vitalii-andriiovskyi** [comment]
Hi @Santoshah.

It seems you had mistaken the libraries. You showed the code with the usage of the library [`ngx-owl-carousel`](https://www.npmjs.com/package/ngx-owl-carousel). 

My library is `ngx-owl-carousel-o`. To start with it you have to write different code. Check [Get started with `ngx-owl-carousel-o`](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#get-started), please.

My library doesn't export the object `OwlCarousel`.

**Comment by Santoshah** [comment]
Oh thanks for making it clear. 

But now I have used your code `ngx-owl-carousel-o` and still having same issue.

```  
<owl-carousel-o [options]="customOptions" class="['bannerList','owl-theme', 'row', 'sliding']">
        <ng-template carouselSlide *ngFor="let item of bannerList"><app-banners></app-banners></ng-template>  
      </owl-carousel-o>

bannerList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  customOptions: OwlOptions = {
    loop: true,
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    dots: false,
    navSpeed: 700,
    navText: ['', ''],
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      740: {
        items: 3
      },
      940: {
        items: 1
      }
    },
    nav: true
  }```

**Comment by vitalii-andriiovskyi** [comment]
Hi @Santoshah.

I think the problem emerges with your `<app-banners></app-banners>`.
Because when you change it into `<div>{{item}}</div>`: 
```html
<owl-carousel-o [options]="customOptions">
  <ng-template carouselSlide *ngFor="let item of bannerList">
    <div>{{item}}</div>
  </ng-template>  
</owl-carousel-o>
```
there's no problem described by you.

Also this code `class="['bannerList','owl-theme', 'row', 'sliding']"` is useless. There's no possibility to add custom classes to the DOM-element `.owl-carousel`. You have to either overwrite default styles or wrap the carousel into DOM-element with needed class and define your css-styles.

**Comment by Santoshah** [comment]
Hi @vitalii-andriiovskyi ,

Thank you for your response.

The app-banners has very simple code that loops with *ngFor. I am just trying to setup a demo that work for now so later I will use real data.

`bannerList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];`

The `{{item}}` will simply get series of number from `bannerList` variable.

<app-banners> code
-------------------------------------------
```<mat-card class="banner-card text-left">
    <img mat-card-image src="assets/img/banners/banner_01.jpg" alt="Banners">
</mat-card>```


Would you care to share a demo where the plugin is working with full width image in firefox ?

**Comment by vitalii-andriiovskyi** [comment]
Hi @Santoshah.

I think you should try the code with just simple image: 
```html
<owl-carousel-o [options]="customOptions">
  <ng-template carouselSlide *ngFor="let item of bannerList">
    <img src="assets/img/banners/banner_01.jpg" alt="Banners">
  </ng-template>  
</owl-carousel-o>
```

If the width of that image is bigger than the width of `.owl-item` than use set css-rule `max-width: 100%` to that image. If this solution is okay, then the problem is with `<app-banners>`. 

Also check the width of the DOM-element, containing the whole carousel. Maybe it has too large width and the carousel takes its 100% width and then assigns that width to the 1 slide showed on the screen with width bigger than 940px.

**Comment by vitalii-andriiovskyi** [comment]
Also try to put your implementation of `ngx-owl-carousel-o` just in root component of your application or create new application and import in it that implementation of the library and everything needed to show in  slides. Play with different ways of using the carousel customized to your case and you'll see the difference and the source of the problem.

**Comment by Santoshah** [comment]
```
  public innerWidth:any;
  ngOnInit() {
    this.innerWidth = window.innerWidth;
    setTimeout(() => {
      $(".owl-stage-outer").css("width", this.innerWidth - 20);   
    }, 1000);
  }

**Comment by vitalii-andriiovskyi** [comment]
@Santoshah 

There is working example.

To check it do this:
1. Run the command `git clone https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o.git`.
2. Check if you're on the branch `develop`. If not switch to it. 
3. Run the command `ng serve --project=demo-owl-carousel`.
4. Type `http://localhost:4200/`  in url field of Firefox .
5. Go to `Gallery Carousel` page. The link is in the navigation.

The image take full width of the screen and doesn't add the scroll bar. 
Options to the carousel are yours. 
You can view the code in the folder `./apps/demo-owl-carousel/src/app/gallery` or [here](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/tree/develop/apps/demo-owl-carousel/src/app/gallery).

As I mentioned above try to check the width of the DOM-element, containing the whole carousel. Maybe it has too large width and the carousel takes its 100% width and then assigns that width to the 1 slide showed on the screen with width bigger than 940px.
