### ISSUE TITLE
Issues with SSR: ReferenceError: Event is not defined

### ISSUE THREAD

**Issue by Rlcolli4** [vitalii-andriiovskyi/ngx-owl-carousel-o#42]
Hello! We have been using ngx-owl-carousel-0 in Angular and in Server Side Rendering with node.js (SSR) and have been happy with it's performance in our application. However, after upgrading to Angular 8 we've had some issues with this node module compiling into our SSR. From what I've been able to find looking at our server.js file (which we use to handle our SSR) and comparing it to the component I think I've found what's causing my specific error:

In "ngx-owl-carousel-o/libs/ngx-owl-carousel-o/src/lib/carousel/carousel.component.ts" lines 263-264 we have the following code:
`@HostListener('document:visibilitychange', ['$event'])`
`onVisibilityChange(ev: Event) {`

When it is compiled into server.js for use with SSR it outputs the following:
`Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__decorate"])([`
	`Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["HostListener"])('document:visibilitychange', ['$event']),`
	`Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:type", Function),`
	`Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [Event]),`
	`Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:returntype", void 0)`
`]`

When you try to run the server.js after it gets compiled you get the error `ReferenceError: Event is not defined` it appears this is related to an issue with Angular Universal ([click here for issue](https://github.com/angular/universal/issues/830)) where items like 'document', 'Document' (Angular typing), 'Event', and 'window' all have issues in SSR. 

I've been part of a discussion where we were able to see another one of our issues ("Document is not defined") fixed by changing how private document variable was set in the application and then loaded in server.js ([here is the issue discussion](https://github.com/themyth92/ngx-lightbox/issues/25), here is the [pull request](https://github.com/themyth92/ngx-lightbox/pull/37/files) for the fix).

I know also swapping the 'Event' type for 'any' would fix it as well but would like an official solution to the issue. This error prevents our server.js file from running killing not just server side rendering but the rest of our applications backend preventing us from being able to run. Thank you in advance for taking the time to review this issue and I hope we can come to a solution soon.

**Comment by cozzbie** [comment]
When did you start noticing this issue? @Rlcolli4

**Comment by vitalii-andriiovskyi** [comment]
Hi, @Rlcolli4.
The solution to this problem is described in docs [Issue with Angular Universal and Solution](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#issue-with-angular-universal-and-solution)

**Comment by Rlcolli4** [comment]
@vitalii-andriiovskyi thanks, I think I might have missed that when reviewing your docs earlier. Next time I have a chance to try it out I'll let you know if it worked.

**Comment by vitalii-andriiovskyi** [comment]
Published new versions of the lib which avoid the reason of the issue.

Choose the right version to your project using the [compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility).
