### ISSUE TITLE
Runtime error in Ivy mode with Angular 9-next.5

### ISSUE THREAD

**Issue by sergey-morenets** [vitalii-andriiovskyi/ngx-owl-carousel-o#45]
Hi

I tried to migrate from "ngx-owl-carousel" to "ngx-owl-carousel-o" (2.0.1). However I have a lot of runtime issues when running my application in Ivy mode (Angular 9-next.5):

```
There are no slides to show. So the carousel won't be rendered.
 ERROR Error: Template error: Can't bind to 'ngClass' since it isn't a known property of 'div'
ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'div'
ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'ng-container'.
```

**Comment by vitalii-andriiovskyi** [comment]
Closing the issue as Angular 9.0.0-rc.6 has released. 

There's similar problem in it (`There are no slides to show. So the carousel won't be rendered`). 
[The solution of it](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#angular-9)
