### ISSUE TITLE
ReferenceError: Event is not defined using NestJS Server to SSR

### ISSUE THREAD

**Issue by jorgeluis1706** [vitalii-andriiovskyi/ngx-owl-carousel-o#46]
Hi, i am using your plugin for my website, but i can't build my project recently because npm run serve does not run correctly.

I have seen that in the repository there is a solution for this issue , but it is a solution oriented for an express server and in the project I am using a server with NestJS.

If you can give me a hand I would greatly appreciate it.

**Comment by vitalii-andriiovskyi** [comment]
Hi @jorgeluis1706.

The solution provided in docs is about using native Node.js features, the library `domino` and defining the global property `Event`. This solution should work in `NestJS` as well. I used express server as an example because the Angular Universal's docs use express server.

```typescript
// -----------------------------------------------------------------------------------
import { readFileSync } from 'fs'; // import readFileSync            (1)
const domino = require('domino');  // import the library `domino`    (2)
// -----------------------------------------------------------------------------------

const DIST_FOLDER = join(process.cwd(), 'dist/browser');

// -----------------------------------------------------------------------------------
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template (3)
const win = domino.createWindow(template); // create object Window                     (4)
global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`   (5)
// -----------------------------------------------------------------------------------

```

However I see the function [`applyDomino`](https://github.com/nestjs/ng-universal/blob/master/lib/utils/domino.utils.ts) in NestJS. It does the 3rd and 4th steps from my example. Also it defines `global['window'] = win;`. 
Looking at this your solution can be:
```typescript
const BROWSER_DIR = join(process.cwd(), 'dist/browser');
applyDomino(global, join(BROWSER_DIR, 'index.html'));
// ------------------------------------------------------------------------------------
global['Event'] = window.Event;
// ------------------------------------------------------------------------------------
```

You should apply this code in the file `server/app.module.ts`  
```typescript
import { Module } from '@nestjs/common';
import { AngularUniversalModule, applyDomino } from '@nestjs/ng-universal';
import { join } from 'path';
import { AppController } from './app.controller';

const BROWSER_DIR = join(process.cwd(), 'dist/browser');
applyDomino(global, join(BROWSER_DIR, 'index.html'));
global['Event'] = window.Event;            //  define the global property `Event`

@Module({
  imports: [
    AngularUniversalModule.forRoot({
      viewsPath: BROWSER_DIR,
      bundle: require('../server/main'),
      liveReload: true,
    }),
  ],
  controllers: [AppController],
})
export class ApplicationModule {}

```

**Comment by jorgeluis1706** [comment]
Thanks for your response, i put the code in my project and the code return the error:

<img width="1002" alt="Screen Shot 2019-10-08 at 2 21 06 PM" src="https://user-images.githubusercontent.com/19720202/66422003-e5d93000-e9d6-11e9-863d-5e1caacacea5.png">

**Comment by smaillns** [comment]
Same issue, is there a solution ? thanks

**Comment by vitalii-andriiovskyi** [comment]
The solution of this problem is:
`global['Event'] = global['window']['Event'];`

`server/app.module.ts`
```typescript
const BROWSER_DIR = join(process.cwd(), 'dist/browser');
applyDomino(global, join(BROWSER_DIR, 'index.html'));
global['Event'] = global['window']['Event'];           //  define the global property `Event`
```

**Comment by vitalii-andriiovskyi** [comment]
Published new versions of the lib which avoid the reason of the issue.

Choose the right version to your project using the [compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility).
