### ISSUE TITLE
ngx-owl-carousel-o Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Sachin124** [vitalii-andriiovskyi/ngx-owl-carousel-o#5]
![img_20181122](https://user-images.githubusercontent.com/26019527/48894643-3dc38280-ee69-11e8-8550-c70e49c7730a.png)

I am using Angular Version 7 (latest), I Install your latest version using `npm i ngx-owl-carousel-o @latest`
command.

My HTML Source Code Is as:

```
<div>Some tags before</div>
    <owl-carousel-o [options]="customOptions">
 
    <ng-container *ngFor="let row of instituteDetails.gallery">
      <ng-template carouselSlide [id]="row.photos_id">
        <img [src]="row.photos_name" >
      </ng-template>
    </ng-container>
 
  </owl-carousel-o>
  <div>Some tags after</div>
```

but I dont Know why this error is happened?

**Comment by vitalii-andriiovskyi** [comment]
V1.0.1 solves this issue.
