### ISSUE TITLE
Support slideTransition

### ISSUE THREAD

**Issue by elion** [vitalii-andriiovskyi/ngx-owl-carousel-o#50]
Currently slideTransition property is missing from OwlOptions. Is there any plan to add it?

**Comment by vitalii-andriiovskyi** [comment]
Hi @elion 

I'll add this option within 1-2 moths.

**Comment by vitalii-andriiovskyi** [comment]
Hi @elion 
The option `slideTransition` is added to `OwlOptions`. Install the latest version `v2.0.2`
