### ISSUE TITLE
How to remove padding on first and last child of carousel when using stagePadding and loop=false

### ISSUE THREAD

**Issue by albinjoseph1994** [vitalii-andriiovskyi/ngx-owl-carousel-o#53]
I want to get my first item and last item without padding while using loop =false

**Comment by vitalii-andriiovskyi** [comment]
Hi @albinjoseph1994 

Set `stagePadding` to 0 or remove this option at all.

**Comment by albinjoseph1994** [comment]
I need stagepadding feature for all items except for first child and last child of array of items when loop is false.

**Comment by vitalii-andriiovskyi** [comment]
The option `stagePadding` is created in order to add `pading-left` and `padding-right` to the `div.owl-stage`.  
For now there's no option to set `padding-left` to `0`, when the first slide becomes visible, and `padding-right` to `0` when the last slide becomes visible.
