### ISSUE TITLE
ReferenceError: Event is not defined  at node_modules/ngx-owl-carousel-o/bundles/ng:/ngx-owl-carousel-o/lib/carousel/carousel.component.ts:266:26

### ISSUE THREAD

**Issue by lifehappensoutdoors** [vitalii-andriiovskyi/ngx-owl-carousel-o#64]
Hey Vitalii,
Thank you for this nice component. I'm having a hard time implementing the fix you published https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#issue-with-angular-universal-and-solution

This is my server.ts file in the image

I'm using "@nguniversal/express-engine": "^8.2.6"

Any help is appreciated.

Thank you!
![Screen Shot 2020-01-14 at 6 33 34 PM](https://user-images.githubusercontent.com/14110389/72362853-8b99ea80-36fc-11ea-95d6-32e313a47661.png)

**Comment by vitalii-andriiovskyi** [comment]
Hi @lifehappensoutdoors 

You wrote `global['Event'] = win.event;`
But it should be `global['Event'] = win.Event;` ---> capital letter `E` in `Event`

**Comment by lifehappensoutdoors** [comment]
I've tried so many combinations, including win.Event but nothing worked. Is there any way around it? Another possible fix?

**Comment by vitalii-andriiovskyi** [comment]
I don't know another solution. 
Try to print to the console `win` and  `win.Event`.

My testing example uses domino `v2.1.3`.

`console.log(win.Event)` gives output: 
```javascript
function Event(type, dictionary) {
  // Initialize basic event properties
  this.type = '';
  this.target = null;
  this.currentTarget = null;
  this.eventPhase = Event.AT_TARGET;
  this.bubbles = false;
  this.cancelable = false;
  this.isTrusted = false;
  this.defaultPrevented = false;
  this.timeStamp = Date.now();

  // Initialize internal flags
  // XXX: Would it be better to inherit these defaults from the prototype?
  this._propagationStopped = false;
  this._immediatePropagationStopped = false;
  this._initialized = true;
  this._dispatching = false;

  // Now initialize based on the constructor arguments (if any)
  if (type) this.type = type;
  if (dictionary) {
    for(var p in dictionary) {
      this[p] = dictionary[p];
    }
  }
}

```

**Comment by lifehappensoutdoors** [comment]
Nothing works and I can get the console to print... Thank you for your support Vitalii!
Will there be a release to fix that problem?

**Comment by vitalii-andriiovskyi** [comment]
Actually this is not the problem of the library. `Event` is browser-only global and therefore it works on frontend. But Node.js  doesn't have a DOM for DOM Events. 

So it's needed to polyfill `Event`. The solution given in docs does this. Maybe there're other ways to do that. Typings `: Event` won't be changed to `any` in the source of the lib. 

Maybe this could be good for your case. You can define what components should get rendered on the server side. If the piece of the app using `ngx-owl-carousel-o` isn't essential, you can avoid rendering it. Details about what to render  on the server and what to not are in the [Why a Fine-Grained Universal Application Shell?](https://blog.angular-university.io/angular-universal/#whyafinegraineduniversalapplicationshell)

**Comment by krupasavadiya** [comment]
We are using angular universal 9 and owl carousel and facing same issue as describe in owl carousel documentation.

Also change our server.ts file as described in documentation

But still facing same issue.

So can any one provide solution???

Here is my server.ts file:

```
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync, readFileSync } from 'fs';
const domino = require('domino');

// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  const DIST_FOLDER = join(process.cwd(), 'dist/browser');
  const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template (3)
  const win = domino.createWindow(template); // create object Window                     (4)
  global['Event'] = win.Event;  

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', DIST_FOLDER);

  // Example Express Rest API endpoints
  // app.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(DIST_FOLDER, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
```

**Comment by vitalii-andriiovskyi** [comment]
@krupasavadiya 
can you debug `win`,  `win.Event` and `global['Event']` or print it to the console and to see what they are.

And how can I reproduce your problem? Do you have example, that I can run and see what's going on?

**Comment by pappkamerad** [comment]
as this is not working with the new SSR for Angular 9 (`Event` needs to be available in `dist/server/main.js` before server.ts executes), can you not simply remove the parameter? it seems to be not used...

https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/develop/libs/ngx-owl-carousel-o/src/lib/carousel/carousel.component.ts#L266

**Comment by pappkamerad** [comment]
meanwhile you can add `global['Event'] = {};` in your main.server.ts

**Comment by grinkarthi** [comment]
> 
> 
> meanwhile you can add `global['Event'] = {};` in your main.server.ts

Thanks for the reply. I am getting the same error even after trying this.

**Comment by jasim08** [comment]
> meanwhile you can add `global['Event'] = {};` in your main.server.ts

Thanks its working now!

**Comment by grinkarthi** [comment]
> 
> 
> > meanwhile you can add `global['Event'] = {};` in your main.server.ts
> 
> Thanks for the reply. I am getting the same error even after trying this.

Thank you. It works. we need to add this to top of the server.ts file.

**Comment by vitalii-andriiovskyi** [comment]
Put this:
``` typescript
const domino = require('domino');  // import the library `domino`   
const DIST_FOLDER = join(process.cwd(), 'dist/browser');
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
const win = domino.createWindow(template); // create object Window            
global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`   
```

before the line 
```typescript
  import { AppServerModule } from './src/main.server';
```

The line `import { AppServerModule } from './src/main.server';` pulls the frontend with the `ngx-owl-carousel-o` and `Event` emerges earlier than we assign `global['Event']` to the ` win.Event;`

**Comment by vitalii-andriiovskyi** [comment]
Changed typings `:Event` into `any` on the line `ngx-owl-carousel-o/lib/carousel/carousel.component.ts:266:26` and published new versions of the lib. 

Choose the right version to your project in the [compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility).
