### ISSUE TITLE
Add option to skip _validateItems

### ISSUE THREAD

**Issue by Shad1ks** [vitalii-andriiovskyi/ngx-owl-carousel-o#66]
Hello,

When the carousel has fewer items than provided in options, the function _validateItems reduce it to the current amount of items. This makes other items to fill all width and if the item has height depending on width it brokes design. Could you add one more setting, so this check will be skipped?

**Comment by vitalii-andriiovskyi** [comment]
Hi @Shad1ks 

added the option [`skip_validateItems`](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#skip_validateitems).

By default, it's `false`. Set to `true` to skip the check of items.
