### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by connectwithub** [vitalii-andriiovskyi/ngx-owl-carousel-o#67]
I have implemented the owl carousel code as below as per the angular 9 guidelines.
`
<owl-carousel-o [options]="customOptions">
    <ng-template carouselSlide [id]="slide.id" *ngFor="let slide of slides">
      
      <ng-container *ngTemplateOutlet="template; context:{slide:slide}"></ng-container>
    </ng-template>
</owl-carousel-o>
`
Everything renders fine but when i click, drag or even autoplay the slides it throws the following error
![image](https://user-images.githubusercontent.com/42773575/73355482-3d6d1580-42be-11ea-9a3d-5e031626abcb.png)
After some debugging i have traced back the error to Owl-Stage>ngStyle>transform function
Have tried everything from custom navigation to auto navigation but nothing seems to work.

Angular Version: Anguar 9-rc-11 
ngx-owl-carousel-0: 2.0.3

**Comment by vitalii-andriiovskyi** [comment]
Hi @connectwithub 

I published `v3.0.0` for the Angular 9. The implementation of the lib could be the same as for other previous versions of Angular. In my test projects, the lib works well.

**Comment by connectwithub** [comment]
Will give it a go and check

**Comment by connectwithub** [comment]
Still, the same issue is happening.
It works for statically provided slide content but not dynamically provided via template

**Comment by connectwithub** [comment]
Update: if the content is wrapped in a div it starts to show up and work correctly like shown below
`<div>
      <ng-container *ngTemplateOutlet="template; context: { slide: slide, slideIndex: slideIndex }"></ng-container>
    </div>`

But in my opinion, it should still work if provided directly or it should be mentioned in the docs atleast

**Comment by TheCoderFish** [comment]
@vitalii-andriiovskyi these needs to be addressed somewhere in the docs as @connectwithub  mentioned. I could only land up here due to the expression has changed error or else would not have been able to find a solution
