### ISSUE TITLE
Programatically move to a given slide i.e. by id?

### ISSUE THREAD

**Issue by yannpiot** [vitalii-andriiovskyi/ngx-owl-carousel-o#70]
I am fetching some data asynchronously in my component. This data should dictate some of the carousel options what slide opens by default (`OwlOptions.startPosition`).

Currently, `OwlOptions` are required from the template when the component is constructed and it seems the carousel is not updating option changes at runtime. Is there a way to programatically move to a given slide i.e. by id and/or change options in general?

**Comment by shahzadpydev** [comment]
Yes @yannpiot we can change slide programmatically by using id

example.component.html
`
<owl-carousel-o [options]="customOptionsforslider" #owlcar>        
     <div id="custom-id">
      </div>
</owl-carousel-o>
`
example.component.ts

```
        import { ViewChild} from '@angular/core';
	@ViewChild("owlCar") owlCar;

  	export class ExampleComponent implements OnInit {
	 ngOnInit() {
	     this.owlCar.next() // move to next side
	     this.owlCar.prev() // move to prev side
	     this.owlCar.to('custom-id')   // move to specific side using id
	  }
	}
```

**Comment by vitalii-andriiovskyi** [comment]
And @yannpiot  id's must have the type `string`.
