### ISSUE TITLE
Error In Angular 9 SSR Build after upgrade from A8

### ISSUE THREAD

**Issue by Sakthisivaprakash** [vitalii-andriiovskyi/ngx-owl-carousel-o#74]
`ReferenceError: Event is not defined
    at Module.bhfF (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3789609)
    at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)
    at Object.PCNd (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3016695)
    at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)
    at Object.ct+p (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:4066756)
    at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)
    at Object.ZAI4 (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3572525)
    at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)
    at Object.24aS (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:946344)
    at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)`
Got Error Even after updating the code provided in the document...

**Comment by jasim08** [comment]
We facing same issue. Please fix this ASAP.

**Comment by jasim08** [comment]
> `ReferenceError: Event is not defined at Module.bhfF (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3789609) at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295) at Object.PCNd (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3016695) at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295) at Object.ct+p (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:4066756) at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295) at Object.ZAI4 (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:3572525) at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295) at Object.24aS (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:946344) at __webpack_require__ (D:\Projects Files\Office Site\Infini-Upgraded\2.0.9\2.0\dist\server\main.js:1:295)`
> Got Error Even after updating the code provided in the document...
Finally I got solution:
defined global['Event'] = {};

if you face any issue use my server.ts file


=====================server.ts======================================
global['Event'] = {};
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
// -----------------------------------------------------------------------------------

const domino = require('domino');  // import the library `domino`    (2)
// -----------------------------------------------------------------------------------
 
import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
  // -----------------------------------------------------------------------------------
 
   const win = domino.createWindow(indexHtml); // create object Window                     (4)
   global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`   (5)
// -----------------------------------------------------------------------------------

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // app.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';

**Comment by vitalii-andriiovskyi** [comment]
Put this:
``` typescript
const domino = require('domino');  // import the library `domino`   
const DIST_FOLDER = join(process.cwd(), 'dist/browser');
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
const win = domino.createWindow(template); // create object Window            
global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`   
```

before the line 
```typescript
  import { AppServerModule } from './src/main.server';
```

The line `import { AppServerModule } from './src/main.server';` pulls the frontend with the `ngx-owl-carousel-o` and `Event` emerges earlier than we assign `global['Event']` to the ` win.Event;`

**Comment by Sakthisivaprakash** [comment]
``

**Comment by Sakthisivaprakash** [comment]
> Put this:
> 
> ```ts
> const domino = require('domino');  // import the library `domino`   
> const DIST_FOLDER = join(process.cwd(), 'dist/browser');
> const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
> const win = domino.createWindow(template); // create object Window            
> global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`   
> ```
> 
> before the line
> 
> ```ts
>   import { AppServerModule } from './src/main.server';
> ```
> 
> The line `import { AppServerModule } from './src/main.server';` pulls the frontend with the `ngx-owl-carousel-o` and `Event` emerges earlier than we assign `global['Event']` to the ` win.Event;`

`ERROR in server.ts:11:18 - error TS2304: Cannot find name 'readFileSync'.

11 const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template`

Error still not fixed...

**Comment by vitalii-andriiovskyi** [comment]
@Sakthisivaprakash 

`readFileSync` is the method of `fs` module, that is the part of Node.js Here is the description of [`readFileSync` ](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options). 

To get this method to the project use 
```typescript
import { readFileSync } from fs;
```

**Comment by Sakthisivaprakash** [comment]
@vitalii-andriiovskyi 
Here I have Attached my server.ts code after upgrading to Angular 9. Please give solution to fix in ssr prerender also.
`import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // app.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
`

**Comment by vitalii-andriiovskyi** [comment]
@Sakthisivaprakash 

Put this:
```typescript
import { readFileSync } from `fs`;
const domino = require('domino');  // import the library `domino`   
const DIST_FOLDER = join(process.cwd(), 'dist/browser');
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
const win = domino.createWindow(template); // create object Window            
global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`
```

into `server.ts`. 
```typescript

import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

// vvvvvvvvvvvvvvvvvvvvvvvv --solution-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
import { readFileSync } from `fs`;
const domino = require('domino');  // import the library `domino`   
const DIST_FOLDER = join(process.cwd(), 'dist/browser');
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
const win = domino.createWindow(template); // create object Window            
global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`
// ^^^^^^^^^^^^^^^^^^^^^^^^^ --solution-- ^^^^^^^^^^^^^^^^^^^^^^^^

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
// The Express app is exported so that it can be used by serverless Functions.
export function app() {
const server = express();
const distFolder = join(process.cwd(), 'dist/browser');

```

It should work.

**Comment by vitalii-andriiovskyi** [comment]
Published new versions of the lib which avoid the reason of the issue.

Choose the right version to your project using the [compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility).

**Comment by Sakthisivaprakash** [comment]
> @Sakthisivaprakash
> 
> Put this:
> 
> ```ts
> import { readFileSync } from `fs`;
> const domino = require('domino');  // import the library `domino`   
> const DIST_FOLDER = join(process.cwd(), 'dist/browser');
> const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
> const win = domino.createWindow(template); // create object Window            
> global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`
> ```
> 
> into `server.ts`.
> 
> ```ts
> import 'zone.js/dist/zone-node';
> 
> import { ngExpressEngine } from '@nguniversal/express-engine';
> import * as express from 'express';
> import { join } from 'path';
> 
> // vvvvvvvvvvvvvvvvvvvvvvvv --solution-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
> import { readFileSync } from `fs`;
> const domino = require('domino');  // import the library `domino`   
> const DIST_FOLDER = join(process.cwd(), 'dist/browser');
> const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString(); // use `index.html` as template 
> const win = domino.createWindow(template); // create object Window            
> global['Event'] = win.Event;               // assign the `win.Event` to prop `Event`
> // ^^^^^^^^^^^^^^^^^^^^^^^^^ --solution-- ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> import { AppServerModule } from './src/main.server';
> import { APP_BASE_HREF } from '@angular/common';
> import { existsSync } from 'fs';
> // The Express app is exported so that it can be used by serverless Functions.
> export function app() {
> const server = express();
> const distFolder = join(process.cwd(), 'dist/browser');
> ```
> 
> It should work.

@vitalii-andriiovskyi  Thank you this one fixed my issue....Same wise i'll try updating to the newer version...
