### ISSUE TITLE
routerLink on drag

### ISSUE THREAD

**Issue by edward24689** [vitalii-andriiovskyi/ngx-owl-carousel-o#77]
```
<owl-carousel-o [options]="customOptions2">
    <ng-template carouselSlide
                 *ngFor="let item of list">
        <a [routerLink]="['/',item.id]"><div class=slide-item></div></a>
    </ng-template>
</owl-carousel-o>
```
When using routerLink in slide item, after drag will direct to another page.
How to stop direct action?

**Comment by Topiya** [comment]
@edward24689 I am facing issue like you have mentioned. I have put click on slide, but when I drag slides it is calling click event. Can you please let me know if you have found any solution so far?

**Comment by edward24689** [comment]
> @edward24689 I am facing issue like you have mentioned. I have put click on slide, but when I drag slides it is calling click event. Can you please let me know if you have found any solution so far?

https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#owlrouterlink
You can use owlrouterlink.
