### ISSUE TITLE
dots showing issue

### ISSUE THREAD

**Issue by mahsaml90** [vitalii-andriiovskyi/ngx-owl-carousel-o#8]
when set dots true in options 
there is 2 row of that in view 
anyone knows why?

![qqq](https://user-images.githubusercontent.com/26897907/49218881-dec0b900-f3e6-11e8-93fb-5e544ec66b9a.PNG)

**Comment by vitalii-andriiovskyi** [comment]
The option `dots` is enabled by default. There's no reason to set it to `true`. Remove `dots: true` in your options. Maybe it will help.

**Comment by vitalii-andriiovskyi** [comment]
Find DOM element `.owl-dots.ng-star-inserted` on the rendered page and see how many dots are rendered. 

![trouble_dots](https://user-images.githubusercontent.com/23376582/49222039-76bca380-f3e3-11e8-9975-0b3d2d6e79fe.png)

If there are 3 dots (they have css-class `.owl-dot.ng-star-inserted`), check css-stylings. Maybe the problem with styles

Remove `responsiveClass` from options. It doesn't work. CSS-class `.owl-responsive` which is supposed to be enabled by `responsiveClass` get attached automatically in the case of using the option `responsive`.
Also there's no need in the option `navText` if the option `nav` isn't `true`. Default value of `nav` is `false`.

**Comment by mahsaml90** [comment]
i have checked counts of .owl-dot
there is 3 dots 
but there is css class that is not from my classes

.owl-theme .owl-dots .owl-dot span
 { 
    margin: 5px 7px; 
}

it cause this issue

**Comment by mahsaml90** [comment]
@vitalii-andriiovskyi you are right.  Overwriting styles works. Although I thought the problem was from the options that i have set.

Thank you for your answer. :)
