### ISSUE TITLE
SlideModel doesn't have center property

### ISSUE THREAD

**Issue by arun-maddheshia** [vitalii-andriiovskyi/ngx-owl-carousel-o#86]
when we use `translated` event there is output like below but in `SlideModel` type `center` property is missing. which cause a lint error.

```
{
  id: string; // id of slide
  width: number; // width of slide
  marginL: number; // margin-left of slide
  marginR: number; // margin-right of slide
  center: boolean; // whether slide is centered (has .center)
} 
```

**Comment by vitalii-andriiovskyi** [comment]
Hi @arun-maddheshia 

Fixed. Update the package according to [Compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility)

The latest version is v3.0.1

**Comment by arun-maddheshia** [comment]
@vitalii-andriiovskyi thanx :)
