### ISSUE TITLE
autoplayHoverPause: true causes immediate slide change on every mouse leave

### ISSUE THREAD

**Issue by Talb2005** [vitalii-andriiovskyi/ngx-owl-carousel-o#88]
**Current behaviour:**
If 'autoplayHoverPause' is enabled, whenever the mouse leaves the carousel, the slide immediately changes to the next slide, ignoring the given 'autoplayTimeout'. 

**Expected behaviour:** 
If 'autoplayHoverPause' is enabled, whenever the mouse leaves the carousel, this should resume / restart the 'autoplayTimeout', so that the slide would change in accordance with the 'autoplayTimeout'.

**Comment by gabe72** [comment]
I am also facing the same issue, any fixes?

**Comment by vitalii-andriiovskyi** [comment]
@Talb2005 
@gabe72 

Added option `autoplayMouseleaveTimeout` for the first timeout on mouseleave. By default, its value is `1`. 

You can set it to the that one `autoplayTimeout` has or to `(autoplayTimeout - autoplaySpeed)`, or whatever you want. 

Update the library to `v3.1.0`. This version is still for Angular 9. There will be version for Angular 10 later.

**Comment by Talb2005** [comment]
Great, thank you!
