### ISSUE TITLE
"There are no slides to show. So the carousel won't be rendered"

### ISSUE THREAD

**Issue by Deesus** [vitalii-andriiovskyi/ngx-owl-carousel-o#93]
I'm using Angular 8 + Owl 2 on large app. I tried to follow the guide as mentioned in the 'Get started' docs. I imported the necessary dependencies and whatnot, and I'm iterating over a list of custom components. However, in the browser, there's a large blank space where the carousel should be and I also get the following message in the console: `There are no slides to show. So the carousel won't be rendered`. Any ideas on what's causing this issue?

**Comment by ODanielHernandez** [comment]
did you found the solution?

**Comment by Larbifatach** [comment]
@vitalii-andriiovskyi

**Comment by ant-ia** [comment]
@vitalii-andriiovskyi  i have the same problem of @Deesus with angular 12 and ngx-owl-carousel 6. do u have any tips?

**Comment by ODanielHernandez** [comment]
> @vitalii-andriiovskyi i have the same problem of @Deesus with angular 12 and ngx-owl-carousel 6. do u have any tips?

I encountered the issue a while a ago, don't quite remember how i solved it. But i can give you some tips, that may help, just by looking at my code.

¿can you show how you are using it so i can guide you?

**Comment by ant-ia** [comment]
Hi @ODanielHernandez , trivially: 
`
<owl-carousel-o [options]="myOwlConfig">
  <ng-container *ngFor="let item of items">
    <ng-template carouselSlide>
        
    </ng-template>
  </ng-container>
</owl-carousel-o>`

`  myOwlConfig: OwlOptions = {
    loop: false,
    autoplay: false,
    touchDrag: true,
    mouseDrag: true,
    center: false,
    dots: false,
    autoHeight: false,
    items: 4
  };`

but i think that the problem is related to encapsulation

**Comment by ODanielHernandez** [comment]
ok @ant-ia, have you tried putting the *ngFor in the ng-template?

`
       //Example
       
        <owl-carousel-o [options]="customOptions">
          <ng-template carouselSlide *ngFor="let composition of topItems">
            
          </ng-template>
        </owl-carousel-o>
`

**Comment by ant-ia** [comment]
> ok @ant-ia, have you tried putting the *ngFor in the ng-template?
> 
> ```
>     <owl-carousel-o [options]="myOwlConfig">
>       <ng-template carouselSlide *ngFor="let item of items">
>         
>       </ng-template>
>     </owl-carousel-o>
> ```

@ODanielHernandez  yes, but i have the same issue

**Comment by ODanielHernandez** [comment]
@ant-ia i checked my code and found nothing different that could be, only thing else for you to try is different version. In my case  the project was in angular 7 but i used version 2 of ngx-owl (when the version for angular 7 is 1.2.1).

**Comment by vitalii-andriiovskyi** [comment]
@ant-ia , @ODanielHernandez , @Larbifatach 

this message is shown if `items` array in `<ng-template carouselSlide *ngFor="let item of items">` is empty. Check it firsly, please. 

Render carousel if `items` is populated with data:
```html
<ng-container *ngIf="items.length > 0">
  <owl-carousel-o [options]="myOwlConfig">
      <ng-template carouselSlide *ngFor="let item of items">
        <!-- Render my Items -->
      </ng-template>
    </owl-carousel-o>
</ng-container>


```

**Comment by matte0080** [comment]
I

> @ant-ia , @ODanielHernandez , @Larbifatach
> 
> this message is shown if `items` array in `<ng-template carouselSlide *ngFor="let item of items">` is empty. Check it firsly, please.
> 
> Render carousel if `items` is populated with data:
> 
> ```
> <ng-container *ngIf="items.length > 0">
>   <owl-carousel-o [options]="myOwlConfig">
>       <ng-template carouselSlide *ngFor="let item of items">
>         
>       </ng-template>
>     </owl-carousel-o>
> </ng-container>
> ```

I'm trying this: 

```
<div *ngIf=" collectionFeatured?.length > 0">
  <owl-carousel-o [options]="customOptions">
    <ng-template carouselSlide [width]="350" *ngFor="let feature of collectionFeatured" >
       <!-- Render my Items -->
    </ng-template>
  </owl-carousel-o>
</div>
```

but receive always: **There are no slides to show. So the carousel won't be re-rendered**
"@angular": "~13.3.8",
"ngx-owl-carousel-o": "^7.0.2",

**Comment by vitalii-andriiovskyi** [comment]
@matte0080 

It turns out, I did the mistake. This message is shown everytime the carousel gets created. I'll fix it.

**Comment by vitalii-andriiovskyi** [comment]
@matte0080 

It's fixed. Update `ngx-owl-carousel-o` to `v7.0.4`

**Comment by pontios** [comment]
I have this problem in version 18 every time it is created
