### ISSUE TITLE
Carousel get broken

### ISSUE THREAD

**Issue by akshata456** [vitalii-andriiovskyi/ngx-owl-carousel-o#98]
@vitalii-andriiovskyi  

here i used angular 7 with lazyload module using serverside rendering.When i used "PREBOOT" is third party  for transition state purpose,carousel design get break after page refreshing.Please suggest  earlier.

**Comment by vitalii-andriiovskyi** [comment]
@akshata456 

How can I reproduce your issue?

**Comment by akshata456** [comment]
@vitalii-andriiovskyi  this issue get fixed by firing resize event.Thanks.

**Comment by MahmoudTarekAli** [comment]
please can you clarify how to do this resize event ?! i am facing the same issue

**Comment by lfongaroScp** [comment]
Same here.
